name: Sync with main branch
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - production
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Test
        run: 
          echo "test production"
      
