name: Sync with main branch
on:
  push:
    branches:
      - production
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Test
        run: 
          echo "test"
      
